# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  command = yarn

  command = yarn sync

  # Directory to change to before starting a build.
  base = "packages/claro-app"

  command = yarn build

  publish = "packages/claro-app/dist"
